### ISSUE TITLE
ZWCAD disappearing commands

### ISSUE THREAD

**Issue by gswifort** [CEXT-Dan/PyRx#81]
When you close one document, the `PYLOAD` and `PYRELOAD` commands disappear.

Example steps:
1. Open the document - _the `PYLOAD` command works_
2. Close the document
3. Open new document - _`PYLOAD` command does not work_

There may also be a different order, e.g. open two documents and close one of them, the key is to close one.
Generally, these commands are available, but they do not appear in the tooltips. You can get around this by typing the full command in the command line and right-clicking on the workspace.

**Comment by CEXT-Dan** [comment]
This is a new bug in ZwCAD 2025, do you have 2024 to confirm?

**Comment by gswifort** [comment]
Yes.
In 2024, after applying this sequence, the hints work if we precede them with an underscore: `_PYLOAD`
![image](https://github.com/CEXT-Dan/PyRx/assets/131259064/3a132e86-8b89-41e6-9183-ae3487e9011d)

**Comment by CEXT-Dan** [comment]
I’ve reported this to ZDN, there’s a conflict with commands a lisp functions with the same name
as a workaround, I can rename the lisp functions from pyload, to adspyload
I can do this for all ZwCAD versions or just ZwCAD 2025

**Comment by gswifort** [comment]
It's not that bothersome... I don't know if changing the name of the function will bother anyone. Maybe we should wait for ZDN's response..?

**Comment by CEXT-Dan** [comment]
yes, we can wait for their response

**Comment by CEXT-Dan** [comment]
ID SUP-71769.

**Comment by gswifort** [comment]
Fixed in version *25.00_2024.06.20(#11796-51d6b18355a)_x64*

**Comment by gswifort** [comment]
There is also a service pack for 2024, so I assume they improved it there too, but I haven't tested it.

**Comment by CEXT-Dan** [comment]
> Fixed in version _25.00_2024.06.20(#11796-51d6b18355a)_x64_

I didn't see it in the release note, did you ask?

**Comment by gswifort** [comment]
No, I assumed it was fixed because it worked for me.
I didn't know that you changed `(pyload)` to `(adspyload)` (I thought it was just a proposition) and that it solved the problem. So maybe it really isn't fixed.

**Comment by CEXT-Dan** [comment]
Yeah, it’s not fixed, so the lisp functions are renamed to adspyload, adspyreload and adspyloaded
If you are a paying ZwCAD customer, you should file a support request to them, that will carry more weight than me through ZDN
